# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share_secret.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='share_secret.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12share_secret.proto\"\x85\x01\n\x0bShareSecret\x12\x0e\n\x06secret\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\x12\x11\n\townership\x18\x03 \x01(\t\x12\x13\n\x0bsecret_hash\x18\x04 \x01(\t\x12\x0b\n\x03key\x18\x05 \x01(\t\x12\x11\n\treset_key\x18\x06 \x01(\t\x12\x0e\n\x06public\x18\x07 \x01(\tb\x06proto3')
)




_SHARESECRET = _descriptor.Descriptor(
  name='ShareSecret',
  full_name='ShareSecret',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secret', full_name='ShareSecret.secret', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active', full_name='ShareSecret.active', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ownership', full_name='ShareSecret.ownership', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secret_hash', full_name='ShareSecret.secret_hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='ShareSecret.key', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reset_key', full_name='ShareSecret.reset_key', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='public', full_name='ShareSecret.public', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['ShareSecret'] = _SHARESECRET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShareSecret = _reflection.GeneratedProtocolMessageType('ShareSecret', (_message.Message,), dict(
  DESCRIPTOR = _SHARESECRET,
  __module__ = 'share_secret_pb2'
  # @@protoc_insertion_point(class_scope:ShareSecret)
  ))
_sym_db.RegisterMessage(ShareSecret)


# @@protoc_insertion_point(module_scope)
